### ISSUE TITLE
UX improvement

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/paralink-ui#19]
<img width="1220" alt="image" src="https://github.com/darwinia-network/assethub-bridge-ui/assets/16152305/39ab3fd6-5adc-4e54-9741-946bca09f72b">

The page has three connects: No.1, No.4, and No.5. This setup is quite bothersome as No.1 synchronizes with No.4. I recommend removing No.1.

There's ample space available; therefore, it would be beneficial for items under No.2 and No.3 to display their full names.

Before using this feature, wallet connections must be established first. If not done so, I'm able to enter any data into the 'From' field without restriction. My suggestion is to reposition the 'Sender' and 'Recipient' fields above the 'From' and 'To'.

No.6 is simply a display field rather than an input field. It should have a distinct style in order to set it apart from the others.

**Comment by wuminzhe** [comment]
Agree!
