### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/paralink-ui#25]
<img width="528" alt="image" src="https://github.com/darwinia-network/assethub-bridge-ui/assets/16152305/c417cfc1-a74d-4024-ac2b-f8e9d3b60f46">

The font size `0` is too large; suggest maintaining the original size.

Also, where does the minimum(`0.02`/`0.7`) come from? @jiguantong

**Comment by jiguantong** [comment]
## to Darwinia 0.02U
```
weight_per_second: 1000000000000

units_per_second for ahUSDT: 4000000

fee = units_per_second * baseXcmWeight * 5 / units_per_second 

fee = 4000000 * 1_000_000_000 * 5 / 1000000000000 = 20000 = 0.02U
```
## to AssetHub 0.7U, the min_balance of USDT
code: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/primitives/utility/src/lib.rs#L169

![image](https://github.com/darwinia-network/assethub-bridge-ui/assets/27564714/7f884963-1b93-49e8-867e-af2bc3a64c40)

**Comment by acgxv** [comment]
@JayJay1024 Suggest changing the `Minimum x` to `At least x for fee`/`At least x for tx fee`/`At least x for transaction fee`

**Comment by acgxv** [comment]
Also the `Balance x` to `Available balance x`
