### ISSUE TITLE
Support RING from Darwinia to HydraDX

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/paralink-ui#29]
https://docs.hydration.net/howto_xcm

https://darwinia2.subsquare.io/referenda/2

And do we support safe?

**Comment by JayJay1024** [comment]
> And do we support safe?

Not supported yet.

**Comment by 2xJDubs** [comment]
@JayJay1024 so we can give the community an idea of when they can send RING to Hydration Network, do you have a timeline for it to be ready?  Thank you.

**Comment by JayJay1024** [comment]
> @JayJay1024 so we can give the community an idea of when they can send RING to Hydration Network, do you have a timeline for it to be ready? Thank you.

I plan to have support on UI next week.

**Comment by jiguantong** [comment]
@JayJay1024 FYI
### Transfer RING Darwinia > HydraDX
1. Change `0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000` to the receiver address specified by the user.
2. Change `5000000000000000000` to the units of RING specified by the user.
3. Min RING is 1 RING
4. Make sure the receiver account has 1 HDX.
```
0x210201010100c91f01000101006d6f646c6f6d6e69706f6f6c00000000000000000000000000000000000000000104000001040500130000f4448291634500000000
```
tx: https://darwinia.subscan.io/xcm_message/polkadot-394598bcd7b181c218f5cad44d88681fa2995492

---

### Transfer RING HydraDX > Darwinia
1. Change `100000000000000000000` to the units of RING specified by the user.
2. Change `0xa7f9bc16870b9cca3da9dd0fb4b771f730bcfd7c` to the receiver address specified by the user.
3. Min RING is 5 RING
```
0x89010100010200f91f04050017000010632d5ec76b0501010200f91f0300a7f9bc16870b9cca3da9dd0fb4b771f730bcfd7c00
```
tx: https://darwinia.subscan.io/xcm_message/polkadot-5b12bf2eb31b7ec5411911f285f38590ea47950c

**Comment by hackfisher** [comment]
For evm tx: use the Dispatch precompile to call substrate call

**Comment by 2xJDubs** [comment]
> > @JayJay1024 so we can give the community an idea of when they can send RING to Hydration Network, do you have a timeline for it to be ready? Thank you.
> 
> I plan to have support on UI next week.

Wonderful.  Thank you!
