### ISSUE TITLE
Add to https://dotappstore.com/

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/paralink-ui#33]
https://dotappstore.com/

**Comment by nblogist** [comment]
Feel free to tag be in these kinda issues as well!

Do we have a tagline decided? We can always go on with the Darwinia tag line, Logo and any relevant media would be nice too! For description if we have one that is good else I can just make one up!

**Comment by nblogist** [comment]
CC @1022ranji lmk if you have anything on it!

**Comment by 1022ranji** [comment]
> CC @1022ranji lmk if you have anything on it!CC lmk 如果你有任何内容！

@boundless-forest please help with this.

**Comment by nblogist** [comment]
following up @boundless-forest

**Comment by boundless-forest** [comment]
tagline: A user-friendly asset exchange app in the Polkadot ecosystem.

I came with the tagline above FYI. As for the logo and relevant media links, I think it's okay to use the Darwinia's material.

**Comment by nblogist** [comment]
"Paralink: Effortless Asset Exchange for the Polkadot Network" I think this seems better - thank you for the inspiration @boundless-forest

**Comment by nblogist** [comment]
Congratulations! Paralink is now on dotappstore.com [Link](https://dotappstore.com/project/paralink)
![image](https://github.com/darwinia-network/paralink-ui/assets/35498810/c94363de-40f7-49f4-8d2e-b6cfa1222baa)
