### ISSUE TITLE
ss58 address display

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/paralink-ui#53]
![image](https://github.com/user-attachments/assets/58572ba0-6908-4322-8269-524ed07b2e98)

![image](https://github.com/user-attachments/assets/4c52eb1c-cad2-407f-ab66-09da76063183)

![image](https://github.com/user-attachments/assets/b66673db-70a5-4f07-802f-1d251c1f6165)

When I attempted to test transferring from Hydration to Darwinia, I connected the talisman with my Hydration account, but it displayed the substrate generic format instead of the Hydration account format (which starts with 7xxx).

**Comment by boundless-forest** [comment]
There was another similar issue at https://github.com/ringecosystem/paralink-ui/issues/46; the balance of the RING for hydration still cannot be displayed.

**Comment by JayJay1024** [comment]
I guess there may be some network problems here, and the balance on my side can be obtained.
<img width="426" alt="image" src="https://github.com/user-attachments/assets/9fc2315f-7928-4573-a697-e3d32729c61e">

**Comment by boundless-forest** [comment]
![image](https://github.com/user-attachments/assets/1e62a06e-07bb-421b-a80d-70d6c45eb53b)

Weird, I have the following console error; I'm not sure if that's the reason.
